### ISSUE TITLE
Menu hard to read

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#20]
**Environment:**
Joomla! 4.3.1
JVP setup from Readme

**Goal:** View the JVP navigation menu

**Outcome:**

The menu is hard to read
<img width="1564" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/540eaa41-d433-4a6d-b8a5-47ba16b80af4">

**Comment by mfleeson** [comment]
Please can you try editing the jvp menu module and adding nav-pill as the module class. 

I raised this issue with George and that was his recommendation. If it works for you then I will update the README instructions.

**Comment by sdwjoomla** [comment]
Adding nav-pill to module class did not work. Adding to menu class did.

<img width="1399" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/0cafbaa3-a18e-4f81-9de2-761e11b9af40">
