### ISSUE TITLE
Clicking many menu item yields error "There is no "com_volunteers.j3template" asset of a "style" type in the registry."

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#21]
**Environment:**
Joomla! 4.3.1
PHP 8.1.6 and 8.2.0
JVP setup from Readme

**Goal:** Use the JVP navigation menu to move through the site.

**Outcome:**
Followed the installation instructions in the Readme.md. 
Navigated to the frontend of the test site.
Clicked the following menu items 

- Home
- Board of Directors
- Departments
- Teaems
- Groups
- Joomlers
- Reports
- Help Wanted

displays the error message 
 "There is no "com_volunteers.j3template" asset of a "style" type in the registry."  
<img width="1237" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/8ee48206-fc89-461c-82cd-996c4b708adc">

**Comment by mfleeson** [comment]
Somehow the media folder is not in the final folder. Fixing it.
