### ISSUE TITLE
Joomler Profile Observations, Question, and Issue Upon Saving

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#22]
**Environment:** 
Joomla! 4.3.1
PHP 8.1.6 and 8.2.0
JVP setup from Readme 

**Goal:** Create a Joomler profile

**Outcome:**
1. Unclear if Month should be Nov or November
2. Calendar options seems unnecessary given that it includes year but the field label does not
3. No guidance on image size or type. Unable to upload an image
4. No guidance of what should be entered. USA vs United States, UK or United Kingdom
5. What is Location? 
6. An information box above this field would be helpful to explain JCP Profile 
7. Would be to mention whether or not links are allowed in the Joomla Story since the introduction addresses links

<img width="1134" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/3046ad2d-c400-4644-af4c-1ca937facc7d">
<img width="1390" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/ffaac4e1-6d55-48c4-ba61-d75ea770a856">
<img width="1390" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/ebb90b8b-a343-4116-b74f-ccdba61da600">

Clicking "Create your Joomla profile" yielded an Oops!

<img width="1390" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/5c7b1bb7-63a8-4050-b1dd-870011cb0fd2">

**Comment by mfleeson** [comment]
All of that profile registration code should not have been there. Substituted for article which links to the Joomla Identity system
