### ISSUE TITLE
FAQs - 404 View Not Found

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#23]
**Environment:**
Joomla! 4.3.1
PHP 8.1.6 and 8.2.0
JVP setup from Readme

**Goal:** View FAQs

**Outcome:**
404 Error View Not Found

<img width="1390" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/7827fddb-eff9-4d6c-9212-499db9c1f551">

**Comment by mfleeson** [comment]
The test data is missing from the Sample Plugin. I am currently building and updating it.
