### ISSUE TITLE
Links No Longer Showing as Buttons

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#28]
**Environment:**
Joomla! 4.3.1
PHP 8.0.23
JVP setup from Readme

**Goal:** View Home page

**Outcome:**
The links no longer show as buttons
J4
<img width="1431" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/4640c081-2980-43f7-a361-3fc01db9eef6">

J3 for comparison
<img width="1791" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/4584d6eb-321f-4e22-8809-80779912c77e">

**Comment by mfleeson** [comment]
Fixed
