### ISSUE TITLE
Extra Space and Button Alignment Issues in Header

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#29]
**Environment:**
Joomla! 4.3.1
PHP 8.0.23
JVP setup from Readme

**Goal:** View JVP

**Outcome:**
Extra space at the top of most pages and buttons do not align
Header on most of the pages has a section of grey and the buttons are stacked offset. 
<img width="1414" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/c9ebb827-5385-4f55-92f0-4be97fbfcb17">

Except for the Register and Login pages which look like the image below. No space at the top and the site name is larger.
<img width="1431" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/feb626c2-e392-411b-bf7e-fff7954bb8ac">

**Comment by mfleeson** [comment]
Fixed
