### ISSUE TITLE
Bottom Not Consistent

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#30]
**Environment:**
Joomla! 4.3.1
PHP 8.0.23
JVP setup from Readme

**Goal:** View JVP

**Outcome:**
The bottom of the Meeting Notes, Register and Login pages does not match the other pages

Meeting Notes, Register and Login pages
<img width="1431" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/71b6bf18-6fec-457c-8596-d383980b4625">

Other pages
![image](https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/890c577f-17c0-46f2-a269-17dfb18733b6)

**Comment by mfleeson** [comment]
Fixed
