### ISSUE TITLE
Social Icons Missing From Footer

### ISSUE THREAD

**Issue by sdwjoomla** [joomla-projects/joomla-volunteer-portal#32]
**Environment:**
Joomla! 4.3.1
PHP 8.0.23
JVP setup from Readme

**Goal:** View JVP Home Page

**Outcome:**
No social icons visible

J4
<img width="1465" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/c4a210db-054c-4227-bc15-687315f3e77e">

J3 for reference
<img width="1787" alt="image" src="https://github.com/joomla-projects/joomla-volunteer-portal/assets/72045461/3a86ddfe-5e13-4f68-887e-ad77d78011ac">

**Comment by mfleeson** [comment]
This has now been fixed.
